<a href="https://colab.research.google.com/github/divyansh212/AI-MODELS-/blob/main/Pytorch_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CREATING TENSOR**

In [12]:
#Using Empty
import torch
a=torch.empty(2,3)
#check type
type(a)
#using zeroes
b=torch.zeros(2,3)
#using ones
c=torch.ones(2,3)
#using rand
d=torch.rand(2,3)
#using manual seed
torch.manual_seed(10)
torch.rand(2,3)
#Custsom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
import torch
#arange
a=torch.arange(0,10)
#linspace
b=torch.linspace(0,10,10)
#using eye
c=torch.eye(5)
#using full
torch.full((4,5),6)

tensor([[6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6],
        [6, 6, 6, 6, 6]])

**TENSOR SHAPES**

In [29]:
import torch
r=torch.tensor([[1,2,3,3,4,5,6],[0,7,8,9,23,45,99]])
r.shape
torch.empty_like(r)
torch.zeros_like(r)
torch.ones_like(r)
torch.rand_like(r,dtype=torch.float64)

tensor([[0.5504, 0.9424, 0.3835, 0.6327, 0.5669, 0.3390, 0.9199],
        [0.6169, 0.5496, 0.0861, 0.9698, 0.2477, 0.4534, 0.1549]],
       dtype=torch.float64)

**TENSOR DATA TYPES**


In [27]:
import torch
r=torch.tensor([[1,2,3,3,4,5,6],[0,7,8,9,23,45,99]])
#Finding data type'
x=r.dtype
#assign data type
torch.tensor([1,2,3,4,5],dtype=torch.float64)
#using to
r.to(torch.float32)

tensor([[ 1.,  2.,  3.,  3.,  4.,  5.,  6.],
        [ 0.,  7.,  8.,  9., 23., 45., 99.]])

**MATHEMATICAL OPERATON**

 **SCALAR OPERATION**

In [39]:
import torch
x=torch.rand(2,3)
print(x)
#ADDITION
x+=2
print(x)
#subtraction
x-=2
print(x)
#Multiplication
x*=2
print(x)
#division
x/=2
print(x)
#int division
x=(x*100)//3
print(x)
#mod
x=((x*100)//3)%2
print(x)
#power
x=x**2
print(x)

tensor([[0.0231, 0.3032, 0.1898],
        [0.9811, 0.7662, 0.3325]])
tensor([[2.0231, 2.3032, 2.1898],
        [2.9811, 2.7662, 2.3325]])
tensor([[0.0231, 0.3032, 0.1898],
        [0.9811, 0.7662, 0.3325]])
tensor([[0.0462, 0.6064, 0.3796],
        [1.9621, 1.5324, 0.6649]])
tensor([[0.0231, 0.3032, 0.1898],
        [0.9811, 0.7662, 0.3325]])
tensor([[ 0., 10.,  6.],
        [32., 25., 11.]])
tensor([[0., 1., 0.],
        [0., 1., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.]])


**ELEMENT WISE OPERATION**

In [42]:
import torch
a=torch.rand(3,5)
b=torch.rand(3,5)
#addition
c=a+b
print(c)
#Subtraction
d=a-b
print(d)
#Multiplication
e=a*b
print(e)
#division
f=a/b
print(f)
#power
g=a**b
print(g)
#mod
h=(a*100)//b
print(h)

tensor([[1.0300, 0.5979, 1.6386, 1.4293, 0.9880],
        [1.5363, 0.0976, 0.8402, 0.5993, 1.2179],
        [0.6710, 1.4438, 0.5082, 1.4422, 1.0105]])
tensor([[-0.2508, -0.4068, -0.0531,  0.2613,  0.7767],
        [-0.4065, -0.0419, -0.6399,  0.2957, -0.3217],
        [-0.5786,  0.1760, -0.2538, -0.4703, -0.9643]])
tensor([[0.2495, 0.0480, 0.6706, 0.4937, 0.0933],
        [0.5488, 0.0019, 0.0741, 0.0679, 0.3450],
        [0.0289, 0.5134, 0.0485, 0.4647, 0.0228]])
tensor([[0.6084, 0.1903, 0.9372, 1.4474, 8.3485],
        [0.5815, 0.3993, 0.1353, 2.9477, 0.5821],
        [0.0739, 1.2777, 0.3339, 0.5082, 0.0233]])
tensor([[0.5468, 0.3075, 0.8216, 0.9065, 0.9869],
        [0.5742, 0.7789, 0.1822, 0.8851, 0.5391],
        [0.1464, 0.8749, 0.4559, 0.5015, 0.0242]])
tensor([[ 60.,  19.,  93., 144., 834.],
        [ 58.,  39.,  13., 294.,  58.],
        [  7., 127.,  33.,  50.,   2.]])
